# Generated by Django 6.0.1 on 2026-02-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tourk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documet', models.CharField(max_length=100)),
                ('choice_tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='relation_db.person')),
            ],
        ),
    ]
