# Generated by Django 6.0.1 on 2026-02-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tours',
        ),
        migrations.RemoveField(
            model_name='tourk',
            name='documet',
        ),
        migrations.AddField(
            model_name='person',
            name='tourr',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.CharField(choices=[('Круизный тур', 'Круизный тур'), ('этнический тур', 'этнический тур'), ('религиозный тур', 'религиозный тур'), ('образавательный тур', 'образавательный тур')], max_length=100)),
                ('choice_tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.person')),
            ],
        ),
    ]
