# Generated by Django 6.0.1 on 2026-02-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0002_remove_person_tours_remove_tourk_documet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeoftours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='tourr',
        ),
        migrations.AddField(
            model_name='person',
            name='userr',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='tours',
            field=models.CharField(choices=[('Отличный', 'Отличный'), ('Лучший', 'Лучший'), ('Одекватный', 'Одекватный'), ('НЕ НОРМАЛЬНЫЙ', 'НЕ НОРМАЛЬНЫЙ')], max_length=100),
        ),
    ]
