# Generated by Django 6.0.1 on 2026-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0003_typeoftours_remove_person_tourr_person_userr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='typeoftourss',
            field=models.ManyToManyField(null=True, to='relation_db.typeoftours'),
        ),
    ]
