# Generated by Django 6.0.1 on 2026-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0004_person_typeoftourss'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='typeoftourss',
        ),
        migrations.AddField(
            model_name='tourk',
            name='typeoftours',
            field=models.CharField(choices=[('Круизный тур', 'Круизный тур'), ('этнический тур', 'этнический тур'), ('религиозный тур', 'религиозный тур'), ('образавательный тур', 'образавательный тур')], default='Круизный тур', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ManyToManyField(null=True, to='relation_db.category'),
        ),
        migrations.DeleteModel(
            name='typeoftours',
        ),
    ]
