# Generated by Django 6.0.1 on 2026-02-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0006_alter_review_choice_tour_alter_tourk_choice_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='choice_tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.person'),
        ),
        migrations.AlterField(
            model_name='tourk',
            name='choice_tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='relation_db.person'),
        ),
    ]
