# Generated by Django 4.2.11 on 2026-02-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0007_alter_review_choice_tour_alter_tourk_choice_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tourk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tourk',
            name='typeoftours',
            field=models.CharField(choices=[('Круизный тур', 'Круизный тур'), ('этнический тур', 'этнический тур'), ('религиозный тур', 'религиозный тур'), ('образавательный тур', 'образавательный тур')], max_length=100),
        ),
    ]
