# Generated by Django 6.0.1 on 2026-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='')),
                ('boi', models.TextField(blank=True, verbose_name='')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='crated_date_lang',
            field=models.PositiveIntegerField(blank=True, verbose_name='год выпуска книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book/', verbose_name='изображение книги'),
        ),
    ]
