# Generated by Django 4.2.11 on 2026-02-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_alter_book_crated_date_lang_alter_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги '},
        ),
        migrations.AddField(
            model_name='book',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='book',
            name='boi',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
        migrations.AddField(
            model_name='book',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО Автора'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='ratiog',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='оценка 1-10'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
